#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Creates a new task into the project directory.
##?
##? Usage:
##?    add <title> [<project>] [--parent=<parent>] [--type=<type>] [--open] [--quite]
docs::parse "$@"

project_tpl_path="$DEEPTHOUGHT_PATH/Templates"

if [ -n "$parent" ]; then
	# If parent is true, display the project selector, if not assume the
	# project name is provided by the user.
	if [ "$parent" == true ]; then
		parent=$(ls --color=never "$DEEPTHOUGHT_PATH/Projects/" | fzf)
	fi
	# validate the parent project path.
	if [ ! -d "$DEEPTHOUGHT_PATH/Projects/$parent" ]; then
		echo "Given parent project does not exists."
		exit
	fi
	projects_base_path="$DEEPTHOUGHT_PATH/Projects/$parent/Projects"
else
	projects_base_path="$DEEPTHOUGHT_PATH/Projects"
fi

if [ -z "$project" ]; then
	project=$(ls --color=never "$projects_base_path" | fzf)
fi

if [ ! -d "$projects_base_path/$project" ]; then
	echo "Given parent project does not exists."
	exit
fi

task_new_path="$projects_base_path/$project/Tasks"

# Create the task directory (idempotently).
mkdir -p "$projects_base_path/$project/Tasks"

count=$(ls "$task_new_path" -1 | wc -l)
count=$((count + 1)) # "cast" to integer
if [ "$count" -eq 0 ]; then
	count=1
fi
# format the task count number
count=$(printf "%03d" "$count")

code=$(cat "$projects_base_path/$project/$project.md" | grep -m 1 "code:" | cut -d ' ' -f 2)
timestamp=$(date +"%Y-%m-%dT%H:%M:%S%z")

type=${type:-task}
if [ "$type" != "task" ]; then
	type="tasks/$type"
fi

title=${title:-undefined}
open=${open:-false}
quite=${quite:-false}

task_id="$code-$count"

if [ "$quite" == false ]; then
	echo "Task: $task_id"
	echo "Project: $project"
	echo "Path: $task_new_path"
fi

# create the task file.
cp "$project_tpl_path/$type.md" "$task_new_path/$task_id.md"

# Replace the keys from the templates.
sed -i 's/<%title%>/'"$title"'/g' "$task_new_path/$task_id.md"
sed -i 's/<%timestamp%>/'"$timestamp"'/g' "$task_new_path/$task_id.md"
sed -i 's/<%task-id%>/'"$task_id"'/g' "$task_new_path/$task_id.md"
sed -i 's/<%status%>/pending/g' "$task_new_path/$task_id.md"

if [ "$quite" == false ]; then
	echo "Task created successfully!"
fi

if [ "$open" == true ]; then
	cd "$task_new_path"
	nvim "$code-$count.md"
fi
