#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Creates a new project into the projects index.
##?
##? Usage:
##?    add <project> [--open] [--code=<code>] [--type=<type>] [--priority=<priority>] [--contract=<contract>] [--index-only] [--quite] [--parent=<parent>]
docs::parse "$@"

title=${project:-unknown}

# if code is not provided try to compute it using the name and project type.
if [ -z "$code" ]; then
	private_code=$(echo "$title" | sed -e 's/$/ /' -e 's/\([^ ]\)[^ ]* /\1/g' -e 's/^ *//')
	code="${private_code^^}"
fi

type=${type:-website}
contract=${contract:-development}
priority=${priority:-high}
index_only=${index_only:-false}
open=${open:-false}
quite=${quite:-false}

project_tpl_path="$DEEPTHOUGHT_PATH/Templates"

if [ -n "$parent" ]; then
	# If parent is true, display the project selector, if not assume the
	# project name is provided by the user.
	if [ "$parent" == true ]; then
		parent=$(ls --color=never "$DEEPTHOUGHT_PATH/Projects/" | fzf)
	fi
	# validate the parent project path.
	if [ ! -d "$DEEPTHOUGHT_PATH/Projects/$parent" ]; then
		echo "Given parent project does not exists."
		exit
	fi
	project_new_path="$DEEPTHOUGHT_PATH/Projects/$parent/Projects/$title"
else
	project_new_path="$DEEPTHOUGHT_PATH/Projects/$title"
fi

if [ "$quite" == false ]; then
	echo "Name: $title ($code)"
	echo "Type: ${type}"
	echo "Contract: ${contract}"
	echo "Path: ${project_new_path}"
fi

# Create the main directory.
mkdir -p "$project_new_path"

# Create the main markdown file, this is the actual index.
cp "$project_tpl_path/project.md" "$project_new_path/$title.md"

# Replace the keys from the templates.
sed -i 's/{{title}}/'"$project"'/g' "$project_new_path/$title.md"
sed -i 's/<%title%>/'"$project"'/g' "$project_new_path/$title.md"
sed -i 's/<%type%>/'"$type"'/g' "$project_new_path/$title.md"
sed -i 's/<%code%>/'"$code"'/g' "$project_new_path/$title.md"
sed -i 's/<%contract%>/'"$contract"'/g' "$project_new_path/$title.md"
sed -i 's/<%priority%>/'"$priority"'/g' "$project_new_path/$title.md"

if [ "$index_only" == false ]; then
	mkdir -p "$project_new_path"/{Content,Tasks,images}
fi

if [ "$quite" == false ]; then
	echo "Project created successfully!"
fi

if [ "$open" == true ]; then
	cd "$project_new_path"
	nvim "$title.md"
fi
