[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
bold.family = "JetBrainsMono Nerd Font Mono"
italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.family = "JetBrainsMono Nerd Font Mono"
size = 15

[window]
opacity = 0.9
blur = true

[terminal]
shell.program = "/opt/homebrew/bin/tmux"
shell.args = ["new-session", "-A", "-D", "-s", "main"]

